// RobotBuilder Version: 1.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.
package org.usfirst.frc5163.Robot;
import org.usfirst.frc5163.Robot.commands.*;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;
import edu.wpi.first.wpilibj.*;
import edu.wpi.first.wpilibj.buttons.*;
/**
 * This class is the glue that binds the controls on the physical operator
 * interface to the commands and command groups that allow control of the robot.
 */
public class OI {
    //// CREATING BUTTONS
    // One type of button is a joystick button which is any button on a joystick.
    // You create one by telling it which joystick it's on and which button
    // number it is.
    // Joystick stick = new Joystick(port);
    // Button button = new JoystickButton(stick, buttonNumber);
    
    // Another type of button you can create is a DigitalIOButton, which is
    // a button or switch hooked up to the cypress module. These are useful if
    // you want to build a customized operator interface.
    // Button button = new DigitalIOButton(1);
    
    // There are a few additional built in buttons you can use. Additionally,
    // by subclassing Button you can create custom triggers and bind those to
    // commands the same as any other Button.
    
    //// TRIGGERING COMMANDS WITH BUTTONS
    // Once you have a button, it's trivial to bind it to a button in one of
    // three ways:
    
    // Start the command when the button is pressed and let it run the command
    // until it is finished as determined by it's isFinished method.
    // button.whenPressed(new ExampleCommand());
    
    // Run the command while the button is being held down and interrupt it once
    // the button is released.
    // button.whileHeld(new ExampleCommand());
    
    // Start the command when the button is released  and let it run the command
    // until it is finished as determined by it's isFinished method.
    // button.whenReleased(new ExampleCommand());
    
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public JoystickButton trigger;
    public JoystickButton cameraup;
    public JoystickButton cameradown;
    public JoystickButton cameraleft;
    public JoystickButton cameraright;
    public Joystick leftJoystick;
    public Joystick rightJoystick;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public OI() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        rightJoystick = new Joystick(2);
        
        leftJoystick = new Joystick(1);
        
        cameraright = new JoystickButton(leftJoystick, 1);
        cameraright.whileHeld(new CameraRotateRight());
        cameraleft = new JoystickButton(leftJoystick, 1);
        cameraleft.whileHeld(new CameraRotateLeft());
        cameradown = new JoystickButton(leftJoystick, 1);
        cameradown.whileHeld(new CameraAngleDown());
        cameraup = new JoystickButton(leftJoystick, 2);
        cameraup.whileHeld(new CameraAngleUp());
        trigger = new JoystickButton(leftJoystick, 1);
        trigger.whenPressed(new realignthecamera());
	    
        // SmartDashboard Buttons
        SmartDashboard.putData("Autonomous Command", new AutonomousCommand());
        SmartDashboard.putData("realign angle", new realignangle());
        SmartDashboard.putData("realign rotation", new realignrotation());
        SmartDashboard.putData("Camera Angle Up", new CameraAngleUp());
        SmartDashboard.putData("Camera Angle Down", new CameraAngleDown());
        SmartDashboard.putData("Camera Rotate Left", new CameraRotateLeft());
        SmartDashboard.putData("Camera Rotate Right", new CameraRotateRight());
        SmartDashboard.putData("Blocker Up", new BlockerUp());
        SmartDashboard.putData("Blocker Down", new BlockerDown());
        SmartDashboard.putData("Ramp Up", new RampUp());
        SmartDashboard.putData("Ramp Position 1", new RampPosition1());
        SmartDashboard.putData("Ramp position 2", new Rampposition2());
        SmartDashboard.putData("realign the camera", new realignthecamera());
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }
    
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS
    public Joystick getLeftJoystick() {
        return leftJoystick;
    }
    public Joystick getrightJoystick() {
        return rightJoystick;
    }
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS
}
