// RobotBuilder Version: 1.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.
package org.usfirst.frc5163.Robot;
    
import edu.wpi.first.wpilibj.*;
import edu.wpi.first.wpilibj.livewindow.LiveWindow;
import java.util.Vector;
/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
public class RobotMap {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public static SpeedController driveTrainRightSide;
    public static SpeedController driveTrainleftSide;
    public static RobotDrive driveTrainWheels;
    public static Servo cameraAngleangle;
    public static Servo cameraRotationRotation;
    public static SpeedController ballLauncherBottom;
    public static SpeedController ballLauncherTop;
    public static Servo blockerleftSide;
    public static Servo blockerrightSide;
    public static Gyro launchRampGyro;
    public static SpeedController launchRampRamp;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public static void init() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        driveTrainRightSide = new Jaguar(1, 2);
	LiveWindow.addActuator("Drive Train", "RightSide", (Jaguar) driveTrainRightSide);
        
        driveTrainleftSide = new Jaguar(1, 1);
	LiveWindow.addActuator("Drive Train", "leftSide", (Jaguar) driveTrainleftSide);
        
        driveTrainWheels = new RobotDrive(driveTrainleftSide, driveTrainRightSide);
	
        driveTrainWheels.setSafetyEnabled(true);
        driveTrainWheels.setExpiration(0.1);
        driveTrainWheels.setSensitivity(0.5);
        driveTrainWheels.setMaxOutput(1.0);
        driveTrainWheels.setInvertedMotor(RobotDrive.MotorType.kRearLeft, true);
        driveTrainWheels.setInvertedMotor(RobotDrive.MotorType.kRearRight, true);        
        cameraAngleangle = new Servo(1, 4);
	LiveWindow.addActuator("Camera Angle", "angle", cameraAngleangle);
        
        cameraRotationRotation = new Servo(1, 5);
	LiveWindow.addActuator("Camera Rotation", "Rotation", cameraRotationRotation);
        
        ballLauncherBottom = new Jaguar(1, 3);
	LiveWindow.addActuator("Ball Launcher", "Bottom", (Jaguar) ballLauncherBottom);
        
        ballLauncherTop = new Jaguar(1, 6);
	LiveWindow.addActuator("Ball Launcher", "Top", (Jaguar) ballLauncherTop);
        
        blockerleftSide = new Servo(1, 7);
	LiveWindow.addActuator("Blocker", "leftSide", blockerleftSide);
        
        blockerrightSide = new Servo(1, 8);
	LiveWindow.addActuator("Blocker", "rightSide", blockerrightSide);
        
        launchRampGyro = new Gyro(1, 1);
	LiveWindow.addSensor("Launch Ramp", "Gyro", launchRampGyro);
        launchRampGyro.setSensitivity(0.007);
        launchRampRamp = new Victor(1, 9);
	LiveWindow.addActuator("Launch Ramp", "Ramp", (Victor) launchRampRamp);
        
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }
}
